### PR TITLE
aix_stanza.py added

### PR DESCRIPTION
**Pull request by flynn1973**
module for manageing aix stanza/config file edits.

### CODE REVIEW

**Comment by kairoaraujo** [comment]
@flynn1973 could you split the changes in different PR?
It will make our reviews and work easier :)

**Comment by flynn1973** [comment]
Ahh…of course, sorry ;-) overmotivated…


________________________________­­­
Christian Tremel
IT-Services der Sozialversicherung GmbH

Rechenzentrum
AIX Systemadministrator
Gruberstraße 77
A – 4021 Linz
T: +43 (0)50124 844 1266
M: +43 (0)664 88661266
christian.tremel@itsv.at<mailto:christian.tremel@itsv.at>
www.itsv.at<http://www.itsv.at>

[https://plattform.sozvers.at/Lists/Schlagzeilen/Attachments/493/CIS-Logo-Signatur.png]


Von: Kairo Araujo [mailto:notifications@github.com]
Gesendet: Montag, 19. November 2018 16:02
An: kairoaraujo/ansible-aix-support <ansible-aix-support@noreply.github.com>
Cc: Tremel Christian <Christian.Tremel@itsv.at>; Mention <mention@noreply.github.com>
Betreff: Re: [kairoaraujo/ansible-aix-support] aix_stanza.py added (#6)


@flynn1973<https://github.com/flynn1973> could you split the changes in different PR?
It will make our reviews and work easier :)

**Comment by kairoaraujo** [comment]
> Ahh…of course, sorry ;-) overmotivated…
You also make me motivated again and we can do many nice modules together!
hacmp, nim, etc :)

**Comment by kairoaraujo** [comment]
@flynn1973 Can you split the` lib/ansible/module_utils/facts/hardware/aix.py` to another PR as we agreed?
I would like to suggest rename the aix_stanza to aix_security, what do you think about?
This evening I will start the reviews, last days were tough.

**Pull request closed without merging**
